import {
  Activity,
  Download,
  Bell,
  Settings,
  X,
  Check
} from "lucide-react";

import { useState } from "react";
import { useNavigate } from "react-router-dom";

function Header() {
  const navigate = useNavigate();

  const [viewMode, setViewMode] = useState("Raw vs. Reconciled");
  const [activityOpen, setActivityOpen] = useState(false);
  const [notificationOpen, setNotificationOpen] = useState(false);

  function downloadBrief() {
    const content = `HORUS - Daily Operations Brief

View: ${viewMode}

Hospital Operations Summary
---------------------------
Occupancy: 88.4%
Physical Beds Open: 29
Net Patient Velocity: +5
Lab TAT: 2.7 hrs
Lost Bed-Hours: 18.5

Generated by HORUS Operations System.
`;

    const blob = new Blob([content], {
      type: "text/plain",
    });

    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");

    link.href = url;
    link.download = "HORUS-Daily-Operations-Brief.txt";

    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    URL.revokeObjectURL(url);
  }

  function toggleViewMode() {
    setViewMode((current) =>
      current === "Raw vs. Reconciled"
        ? "Reconciled Only"
        : "Raw vs. Reconciled"
    );
  }

  function closePanels() {
    setActivityOpen(false);
    setNotificationOpen(false);
  }

  return (
    <>
      <header className="top-header">

        {/* BRAND */}

        <div className="header-brand">
          <img
            src="/logo.png"
            alt="HORUS"
            style={{ width: "32px", height: "32px", objectFit: "contain", borderRadius: "50%", display: "block" }}
          />

          <span className="header-name">HORUS</span>

          <div className="engine-status">
            <span className="pulse-dot" />
            <span>
              Zero-Loss Reconciliation Engine Active
            </span>
          </div>
        </div>

        {/* NAVIGATION */}

        <div className="header-navigation">
          <button
            className="header-active-link"
            type="button"
            onClick={toggleViewMode}
            title="Toggle reconciliation view"
          >
            {viewMode}
          </button>
        </div>

        {/* TOOLS */}

        <div className="header-tools">

          {/* DOWNLOAD */}

          <button
            className="brief-button"
            type="button"
            onClick={downloadBrief}
          >
            <Download size={14} />
            Download Daily Operations Brief
          </button>

          {/* NOTIFICATION */}

          <div className="header-dropdown-wrapper">
            <button
              type="button"
              className="header-tool"
              onClick={() => {
                setNotificationOpen(!notificationOpen);
                setActivityOpen(false);
              }}
            >
              <Bell size={18} />
            </button>

            {notificationOpen && (
              <div className="notification-panel">
                <div className="notification-header">
                  <div>
                    <strong>Notifications</strong>
                    <span>3 unread alerts</span>
                  </div>

                  <button
                    type="button"
                    onClick={() => setNotificationOpen(false)}
                  >
                    <X size={14} />
                  </button>
                </div>

                <div className="notification-list">
                  <div className="notification-item unread">
                    <div className="notification-dot" />
                    <div>
                      <strong>Critical ICU Occupancy</strong>
                      <p>ICU capacity reached 93.3% threshold.</p>
                      <small>2 min ago</small>
                    </div>
                  </div>

                  <div className="notification-item unread">
                    <div className="notification-dot" />
                    <div>
                      <strong>Ghost Bed Reconciled</strong>
                      <p>Bed MED-14 auto-reconciled with physical sensor.</p>
                      <small>15 min ago</small>
                    </div>
                  </div>

                  <div className="notification-item unread">
                    <div className="notification-dot" />
                    <div>
                      <strong>Pharmacy Stock Warning</strong>
                      <p>Meropenem 1g IV stock below safety buffer.</p>
                      <small>1 hr ago</small>
                    </div>
                  </div>
                </div>
              </div>
            )}
          </div>

          {/* ACTIVITY */}

          <button
            className="header-tool"
            type="button"
            title="Activity"
            onClick={() => {
              setActivityOpen(!activityOpen);
              setNotificationOpen(false);
            }}
          >
            <Activity size={18} />
          </button>

          {/* SETTINGS */}

          <button
            className="header-tool"
            type="button"
            title="Settings"
            onClick={() => {
              closePanels();
              navigate("/profile");
            }}
          >
            <Settings size={18} />
          </button>

        </div>

      </header>

      {(notificationOpen || activityOpen) && (
        <div
          className="header-backdrop"
          onClick={closePanels}
        />
      )}
    </>
  );
}

export default Header;
