export const initialWardCensusData = [
  {
    "id": 1,
    "date": "2026-08-29 (Today)",
    "ward": "Emergency Ward 1",
    "capacity": 10,
    "occupancy": "70%",
    "his": 7,
    "manual": 7,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Priya Singh"
  },
  {
    "id": 2,
    "date": "2026-08-29 (Today)",
    "ward": "Emergency Ward 2",
    "capacity": 15,
    "occupancy": "73%",
    "his": 11,
    "manual": 11,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Amit Verma"
  },
  {
    "id": 3,
    "date": "2026-08-29 (Today)",
    "ward": "Emergency Ward 3",
    "capacity": 10,
    "occupancy": "70%",
    "his": 7,
    "manual": 7,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Suresh Das"
  },
  {
    "id": 4,
    "date": "2026-08-29 (Today)",
    "ward": "Emergency Ward 4",
    "capacity": 20,
    "occupancy": "80%",
    "his": 16,
    "manual": 16,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Neha Gupta"
  },
  {
    "id": 5,
    "date": "2026-08-29 (Today)",
    "ward": "Emergency Ward 5",
    "capacity": 20,
    "occupancy": "85%",
    "his": 17,
    "manual": 18,
    "delta": 1,
    "status": "Imputed",
    "nurse": "Nurse Arjun Singh"
  },
  {
    "id": 6,
    "date": "2026-08-29 (Today)",
    "ward": "Internal Medicine Ward 1",
    "capacity": 10,
    "occupancy": "80%",
    "his": 8,
    "manual": 8,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Sunita Patel"
  },
  {
    "id": 7,
    "date": "2026-08-29 (Today)",
    "ward": "Internal Medicine Ward 2",
    "capacity": 15,
    "occupancy": "87%",
    "his": 13,
    "manual": 12,
    "delta": -1,
    "status": "Audit Req",
    "nurse": "Nurse Vikram Malhotra"
  },
  {
    "id": 8,
    "date": "2026-08-29 (Today)",
    "ward": "Internal Medicine Ward 3",
    "capacity": 10,
    "occupancy": "70%",
    "his": 7,
    "manual": 7,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Manish Joshi"
  },
  {
    "id": 9,
    "date": "2026-08-29 (Today)",
    "ward": "Internal Medicine Ward 4",
    "capacity": 10,
    "occupancy": "70%",
    "his": 7,
    "manual": 7,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Kavita Rao"
  },
  {
    "id": 10,
    "date": "2026-08-29 (Today)",
    "ward": "Internal Medicine Ward 5",
    "capacity": 20,
    "occupancy": "75%",
    "his": 15,
    "manual": 16,
    "delta": 1,
    "status": "Imputed",
    "nurse": "Nurse Deepak Choudhary"
  },
  {
    "id": 11,
    "date": "2026-08-29 (Today)",
    "ward": "Surgery Ward 1",
    "capacity": 20,
    "occupancy": "80%",
    "his": 16,
    "manual": 16,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Ananya Mishra"
  },
  {
    "id": 12,
    "date": "2026-08-29 (Today)",
    "ward": "Surgery Ward 2",
    "capacity": 20,
    "occupancy": "80%",
    "his": 16,
    "manual": 16,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Rameshwar Reddy"
  },
  {
    "id": 13,
    "date": "2026-08-29 (Today)",
    "ward": "Surgery Ward 3",
    "capacity": 20,
    "occupancy": "85%",
    "his": 17,
    "manual": 17,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Aarav Sharma"
  },
  {
    "id": 14,
    "date": "2026-08-29 (Today)",
    "ward": "Surgery Ward 4",
    "capacity": 15,
    "occupancy": "87%",
    "his": 13,
    "manual": 12,
    "delta": -1,
    "status": "Audit Req",
    "nurse": "Nurse Geeta Sen"
  },
  {
    "id": 15,
    "date": "2026-08-29 (Today)",
    "ward": "Surgery Ward 5",
    "capacity": 15,
    "occupancy": "93%",
    "his": 14,
    "manual": 15,
    "delta": 1,
    "status": "Imputed",
    "nurse": "Nurse Pooja Hegde"
  },
  {
    "id": 16,
    "date": "2026-08-29 (Today)",
    "ward": "Pediatrics Ward 1",
    "capacity": 10,
    "occupancy": "70%",
    "his": 7,
    "manual": 7,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Rohan Mehra"
  },
  {
    "id": 17,
    "date": "2026-08-29 (Today)",
    "ward": "Pediatrics Ward 2",
    "capacity": 20,
    "occupancy": "75%",
    "his": 15,
    "manual": 15,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Isha Mukherjee"
  },
  {
    "id": 18,
    "date": "2026-08-29 (Today)",
    "ward": "Pediatrics Ward 3",
    "capacity": 15,
    "occupancy": "73%",
    "his": 11,
    "manual": 11,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Sanjay Gupta"
  },
  {
    "id": 19,
    "date": "2026-08-29 (Today)",
    "ward": "Pediatrics Ward 4",
    "capacity": 10,
    "occupancy": "80%",
    "his": 8,
    "manual": 8,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Divya Nair"
  },
  {
    "id": 20,
    "date": "2026-08-29 (Today)",
    "ward": "Pediatrics Ward 5",
    "capacity": 15,
    "occupancy": "80%",
    "his": 12,
    "manual": 13,
    "delta": 1,
    "status": "Imputed",
    "nurse": "Nurse Rajesh Khanna"
  },
  {
    "id": 21,
    "date": "2026-08-29 (Today)",
    "ward": "Orthopedics Ward 1",
    "capacity": 15,
    "occupancy": "87%",
    "his": 13,
    "manual": 12,
    "delta": -1,
    "status": "Audit Req",
    "nurse": "Nurse Swati Deshmukh"
  },
  {
    "id": 22,
    "date": "2026-08-29 (Today)",
    "ward": "Orthopedics Ward 2",
    "capacity": 15,
    "occupancy": "87%",
    "his": 13,
    "manual": 13,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Nitin Gadkari"
  },
  {
    "id": 23,
    "date": "2026-08-29 (Today)",
    "ward": "Orthopedics Ward 3",
    "capacity": 20,
    "occupancy": "90%",
    "his": 18,
    "manual": 18,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Meera Joshi"
  },
  {
    "id": 24,
    "date": "2026-08-29 (Today)",
    "ward": "ICU Ward 1",
    "capacity": 10,
    "occupancy": "70%",
    "his": 7,
    "manual": 7,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Harish Iyer"
  },
  {
    "id": 25,
    "date": "2026-08-29 (Today)",
    "ward": "ICU Ward 2",
    "capacity": 20,
    "occupancy": "75%",
    "his": 15,
    "manual": 16,
    "delta": 1,
    "status": "Imputed",
    "nurse": "Nurse Preeti Pillai"
  },
  {
    "id": 26,
    "date": "2026-08-29 (Today)",
    "ward": "ICU Ward 3",
    "capacity": 15,
    "occupancy": "73%",
    "his": 11,
    "manual": 11,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Karan Singhania"
  },
  {
    "id": 27,
    "date": "2026-08-29 (Today)",
    "ward": "ICU Ward 4",
    "capacity": 20,
    "occupancy": "80%",
    "his": 16,
    "manual": 16,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Tanya Sen"
  },
  {
    "id": 28,
    "date": "2026-08-28 (Yesterday)",
    "ward": "Emergency Ward 1",
    "capacity": 10,
    "occupancy": "70%",
    "his": 7,
    "manual": 7,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Amit Verma"
  },
  {
    "id": 29,
    "date": "2026-08-28 (Yesterday)",
    "ward": "Emergency Ward 2",
    "capacity": 15,
    "occupancy": "73%",
    "his": 11,
    "manual": 11,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Suresh Das"
  },
  {
    "id": 30,
    "date": "2026-08-28 (Yesterday)",
    "ward": "Emergency Ward 3",
    "capacity": 10,
    "occupancy": "80%",
    "his": 8,
    "manual": 8,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Neha Gupta"
  },
  {
    "id": 31,
    "date": "2026-08-28 (Yesterday)",
    "ward": "Emergency Ward 4",
    "capacity": 20,
    "occupancy": "80%",
    "his": 16,
    "manual": 17,
    "delta": 1,
    "status": "Imputed",
    "nurse": "Nurse Arjun Singh"
  },
  {
    "id": 32,
    "date": "2026-08-28 (Yesterday)",
    "ward": "Emergency Ward 5",
    "capacity": 20,
    "occupancy": "85%",
    "his": 17,
    "manual": 17,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Sunita Patel"
  },
  {
    "id": 33,
    "date": "2026-08-28 (Yesterday)",
    "ward": "Internal Medicine Ward 1",
    "capacity": 10,
    "occupancy": "90%",
    "his": 9,
    "manual": 8,
    "delta": -1,
    "status": "Audit Req",
    "nurse": "Nurse Vikram Malhotra"
  },
  {
    "id": 34,
    "date": "2026-08-28 (Yesterday)",
    "ward": "Internal Medicine Ward 2",
    "capacity": 15,
    "occupancy": "93%",
    "his": 14,
    "manual": 14,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Manish Joshi"
  },
  {
    "id": 35,
    "date": "2026-08-28 (Yesterday)",
    "ward": "Internal Medicine Ward 3",
    "capacity": 10,
    "occupancy": "70%",
    "his": 7,
    "manual": 7,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Kavita Rao"
  },
  {
    "id": 36,
    "date": "2026-08-28 (Yesterday)",
    "ward": "Internal Medicine Ward 4",
    "capacity": 10,
    "occupancy": "70%",
    "his": 7,
    "manual": 8,
    "delta": 1,
    "status": "Imputed",
    "nurse": "Nurse Deepak Choudhary"
  },
  {
    "id": 37,
    "date": "2026-08-28 (Yesterday)",
    "ward": "Internal Medicine Ward 5",
    "capacity": 20,
    "occupancy": "75%",
    "his": 15,
    "manual": 15,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Ananya Mishra"
  },
  {
    "id": 38,
    "date": "2026-08-28 (Yesterday)",
    "ward": "Surgery Ward 1",
    "capacity": 20,
    "occupancy": "80%",
    "his": 16,
    "manual": 16,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Rameshwar Reddy"
  },
  {
    "id": 39,
    "date": "2026-08-28 (Yesterday)",
    "ward": "Surgery Ward 2",
    "capacity": 20,
    "occupancy": "85%",
    "his": 17,
    "manual": 17,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Aarav Sharma"
  },
  {
    "id": 40,
    "date": "2026-08-28 (Yesterday)",
    "ward": "Surgery Ward 3",
    "capacity": 20,
    "occupancy": "85%",
    "his": 17,
    "manual": 16,
    "delta": -1,
    "status": "Audit Req",
    "nurse": "Nurse Geeta Sen"
  },
  {
    "id": 41,
    "date": "2026-08-28 (Yesterday)",
    "ward": "Surgery Ward 4",
    "capacity": 15,
    "occupancy": "87%",
    "his": 13,
    "manual": 14,
    "delta": 1,
    "status": "Imputed",
    "nurse": "Nurse Pooja Hegde"
  },
  {
    "id": 42,
    "date": "2026-08-28 (Yesterday)",
    "ward": "Surgery Ward 5",
    "capacity": 15,
    "occupancy": "67%",
    "his": 10,
    "manual": 10,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Rohan Mehra"
  },
  {
    "id": 43,
    "date": "2026-08-28 (Yesterday)",
    "ward": "Pediatrics Ward 1",
    "capacity": 10,
    "occupancy": "70%",
    "his": 7,
    "manual": 7,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Isha Mukherjee"
  },
  {
    "id": 44,
    "date": "2026-08-28 (Yesterday)",
    "ward": "Pediatrics Ward 2",
    "capacity": 20,
    "occupancy": "75%",
    "his": 15,
    "manual": 15,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Sanjay Gupta"
  },
  {
    "id": 45,
    "date": "2026-08-28 (Yesterday)",
    "ward": "Pediatrics Ward 3",
    "capacity": 15,
    "occupancy": "80%",
    "his": 12,
    "manual": 12,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Divya Nair"
  },
  {
    "id": 46,
    "date": "2026-08-28 (Yesterday)",
    "ward": "Pediatrics Ward 4",
    "capacity": 10,
    "occupancy": "80%",
    "his": 8,
    "manual": 9,
    "delta": 1,
    "status": "Imputed",
    "nurse": "Nurse Rajesh Khanna"
  },
  {
    "id": 47,
    "date": "2026-08-28 (Yesterday)",
    "ward": "Pediatrics Ward 5",
    "capacity": 15,
    "occupancy": "87%",
    "his": 13,
    "manual": 12,
    "delta": -1,
    "status": "Audit Req",
    "nurse": "Nurse Swati Deshmukh"
  },
  {
    "id": 48,
    "date": "2026-08-28 (Yesterday)",
    "ward": "Orthopedics Ward 1",
    "capacity": 15,
    "occupancy": "87%",
    "his": 13,
    "manual": 13,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Nitin Gadkari"
  },
  {
    "id": 49,
    "date": "2026-08-28 (Yesterday)",
    "ward": "Orthopedics Ward 2",
    "capacity": 15,
    "occupancy": "87%",
    "his": 13,
    "manual": 13,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Meera Joshi"
  },
  {
    "id": 50,
    "date": "2026-08-28 (Yesterday)",
    "ward": "Orthopedics Ward 3",
    "capacity": 20,
    "occupancy": "70%",
    "his": 14,
    "manual": 14,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Harish Iyer"
  },
  {
    "id": 51,
    "date": "2026-08-28 (Yesterday)",
    "ward": "ICU Ward 1",
    "capacity": 10,
    "occupancy": "70%",
    "his": 7,
    "manual": 8,
    "delta": 1,
    "status": "Imputed",
    "nurse": "Nurse Preeti Pillai"
  },
  {
    "id": 52,
    "date": "2026-08-28 (Yesterday)",
    "ward": "ICU Ward 2",
    "capacity": 20,
    "occupancy": "75%",
    "his": 15,
    "manual": 15,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Karan Singhania"
  },
  {
    "id": 53,
    "date": "2026-08-28 (Yesterday)",
    "ward": "ICU Ward 3",
    "capacity": 15,
    "occupancy": "80%",
    "his": 12,
    "manual": 12,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Tanya Sen"
  },
  {
    "id": 54,
    "date": "2026-08-28 (Yesterday)",
    "ward": "ICU Ward 4",
    "capacity": 20,
    "occupancy": "80%",
    "his": 16,
    "manual": 15,
    "delta": -1,
    "status": "Audit Req",
    "nurse": "Nurse Gaurav Kapoor"
  },
  {
    "id": 55,
    "date": "2026-08-27",
    "ward": "Emergency Ward 1",
    "capacity": 10,
    "occupancy": "70%",
    "his": 7,
    "manual": 7,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Suresh Das"
  },
  {
    "id": 56,
    "date": "2026-08-27",
    "ward": "Emergency Ward 2",
    "capacity": 15,
    "occupancy": "73%",
    "his": 11,
    "manual": 11,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Neha Gupta"
  },
  {
    "id": 57,
    "date": "2026-08-27",
    "ward": "Emergency Ward 3",
    "capacity": 10,
    "occupancy": "80%",
    "his": 8,
    "manual": 9,
    "delta": 1,
    "status": "Imputed",
    "nurse": "Nurse Arjun Singh"
  },
  {
    "id": 58,
    "date": "2026-08-27",
    "ward": "Emergency Ward 4",
    "capacity": 20,
    "occupancy": "85%",
    "his": 17,
    "manual": 17,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Sunita Patel"
  },
  {
    "id": 59,
    "date": "2026-08-27",
    "ward": "Emergency Ward 5",
    "capacity": 20,
    "occupancy": "85%",
    "his": 17,
    "manual": 16,
    "delta": -1,
    "status": "Audit Req",
    "nurse": "Nurse Vikram Malhotra"
  },
  {
    "id": 60,
    "date": "2026-08-27",
    "ward": "Internal Medicine Ward 1",
    "capacity": 10,
    "occupancy": "90%",
    "his": 9,
    "manual": 9,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Manish Joshi"
  },
  {
    "id": 61,
    "date": "2026-08-27",
    "ward": "Internal Medicine Ward 2",
    "capacity": 15,
    "occupancy": "67%",
    "his": 10,
    "manual": 10,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Kavita Rao"
  },
  {
    "id": 62,
    "date": "2026-08-27",
    "ward": "Internal Medicine Ward 3",
    "capacity": 10,
    "occupancy": "70%",
    "his": 7,
    "manual": 8,
    "delta": 1,
    "status": "Imputed",
    "nurse": "Nurse Deepak Choudhary"
  },
  {
    "id": 63,
    "date": "2026-08-27",
    "ward": "Internal Medicine Ward 4",
    "capacity": 10,
    "occupancy": "70%",
    "his": 7,
    "manual": 7,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Ananya Mishra"
  },
  {
    "id": 64,
    "date": "2026-08-27",
    "ward": "Internal Medicine Ward 5",
    "capacity": 20,
    "occupancy": "80%",
    "his": 16,
    "manual": 16,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Rameshwar Reddy"
  },
  {
    "id": 65,
    "date": "2026-08-27",
    "ward": "Surgery Ward 1",
    "capacity": 20,
    "occupancy": "80%",
    "his": 16,
    "manual": 16,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Aarav Sharma"
  },
  {
    "id": 66,
    "date": "2026-08-27",
    "ward": "Surgery Ward 2",
    "capacity": 20,
    "occupancy": "85%",
    "his": 17,
    "manual": 16,
    "delta": -1,
    "status": "Audit Req",
    "nurse": "Nurse Geeta Sen"
  },
  {
    "id": 67,
    "date": "2026-08-27",
    "ward": "Surgery Ward 3",
    "capacity": 20,
    "occupancy": "90%",
    "his": 18,
    "manual": 19,
    "delta": 1,
    "status": "Imputed",
    "nurse": "Nurse Pooja Hegde"
  },
  {
    "id": 68,
    "date": "2026-08-27",
    "ward": "Surgery Ward 4",
    "capacity": 15,
    "occupancy": "93%",
    "his": 14,
    "manual": 14,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Rohan Mehra"
  },
  {
    "id": 69,
    "date": "2026-08-27",
    "ward": "Surgery Ward 5",
    "capacity": 15,
    "occupancy": "67%",
    "his": 10,
    "manual": 10,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Isha Mukherjee"
  },
  {
    "id": 70,
    "date": "2026-08-27",
    "ward": "Pediatrics Ward 1",
    "capacity": 10,
    "occupancy": "70%",
    "his": 7,
    "manual": 7,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Sanjay Gupta"
  },
  {
    "id": 71,
    "date": "2026-08-27",
    "ward": "Pediatrics Ward 2",
    "capacity": 20,
    "occupancy": "75%",
    "his": 15,
    "manual": 15,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Divya Nair"
  },
  {
    "id": 72,
    "date": "2026-08-27",
    "ward": "Pediatrics Ward 3",
    "capacity": 15,
    "occupancy": "80%",
    "his": 12,
    "manual": 13,
    "delta": 1,
    "status": "Imputed",
    "nurse": "Nurse Rajesh Khanna"
  },
  {
    "id": 73,
    "date": "2026-08-27",
    "ward": "Pediatrics Ward 4",
    "capacity": 10,
    "occupancy": "80%",
    "his": 8,
    "manual": 7,
    "delta": -1,
    "status": "Audit Req",
    "nurse": "Nurse Swati Deshmukh"
  },
  {
    "id": 74,
    "date": "2026-08-27",
    "ward": "Pediatrics Ward 5",
    "capacity": 15,
    "occupancy": "87%",
    "his": 13,
    "manual": 13,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Nitin Gadkari"
  },
  {
    "id": 75,
    "date": "2026-08-27",
    "ward": "Orthopedics Ward 1",
    "capacity": 15,
    "occupancy": "87%",
    "his": 13,
    "manual": 13,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Meera Joshi"
  },
  {
    "id": 76,
    "date": "2026-08-27",
    "ward": "Orthopedics Ward 2",
    "capacity": 15,
    "occupancy": "67%",
    "his": 10,
    "manual": 10,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Harish Iyer"
  },
  {
    "id": 77,
    "date": "2026-08-27",
    "ward": "Orthopedics Ward 3",
    "capacity": 20,
    "occupancy": "70%",
    "his": 14,
    "manual": 15,
    "delta": 1,
    "status": "Imputed",
    "nurse": "Nurse Preeti Pillai"
  },
  {
    "id": 78,
    "date": "2026-08-27",
    "ward": "ICU Ward 1",
    "capacity": 10,
    "occupancy": "70%",
    "his": 7,
    "manual": 7,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Karan Singhania"
  },
  {
    "id": 79,
    "date": "2026-08-27",
    "ward": "ICU Ward 2",
    "capacity": 20,
    "occupancy": "75%",
    "his": 15,
    "manual": 15,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Tanya Sen"
  },
  {
    "id": 80,
    "date": "2026-08-27",
    "ward": "ICU Ward 3",
    "capacity": 15,
    "occupancy": "80%",
    "his": 12,
    "manual": 11,
    "delta": -1,
    "status": "Audit Req",
    "nurse": "Nurse Gaurav Kapoor"
  },
  {
    "id": 81,
    "date": "2026-08-27",
    "ward": "ICU Ward 4",
    "capacity": 20,
    "occupancy": "85%",
    "his": 17,
    "manual": 17,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Shreya Ghoshal"
  },
  {
    "id": 82,
    "date": "2026-08-26",
    "ward": "Emergency Ward 1",
    "capacity": 10,
    "occupancy": "70%",
    "his": 7,
    "manual": 7,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Neha Gupta"
  },
  {
    "id": 83,
    "date": "2026-08-26",
    "ward": "Emergency Ward 2",
    "capacity": 15,
    "occupancy": "80%",
    "his": 12,
    "manual": 13,
    "delta": 1,
    "status": "Imputed",
    "nurse": "Nurse Arjun Singh"
  },
  {
    "id": 84,
    "date": "2026-08-26",
    "ward": "Emergency Ward 3",
    "capacity": 10,
    "occupancy": "80%",
    "his": 8,
    "manual": 8,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Sunita Patel"
  },
  {
    "id": 85,
    "date": "2026-08-26",
    "ward": "Emergency Ward 4",
    "capacity": 20,
    "occupancy": "85%",
    "his": 17,
    "manual": 16,
    "delta": -1,
    "status": "Audit Req",
    "nurse": "Nurse Vikram Malhotra"
  },
  {
    "id": 86,
    "date": "2026-08-26",
    "ward": "Emergency Ward 5",
    "capacity": 20,
    "occupancy": "90%",
    "his": 18,
    "manual": 18,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Manish Joshi"
  },
  {
    "id": 87,
    "date": "2026-08-26",
    "ward": "Internal Medicine Ward 1",
    "capacity": 10,
    "occupancy": "90%",
    "his": 9,
    "manual": 9,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Kavita Rao"
  },
  {
    "id": 88,
    "date": "2026-08-26",
    "ward": "Internal Medicine Ward 2",
    "capacity": 15,
    "occupancy": "67%",
    "his": 10,
    "manual": 11,
    "delta": 1,
    "status": "Imputed",
    "nurse": "Nurse Deepak Choudhary"
  },
  {
    "id": 89,
    "date": "2026-08-26",
    "ward": "Internal Medicine Ward 3",
    "capacity": 10,
    "occupancy": "70%",
    "his": 7,
    "manual": 7,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Ananya Mishra"
  },
  {
    "id": 90,
    "date": "2026-08-26",
    "ward": "Internal Medicine Ward 4",
    "capacity": 10,
    "occupancy": "70%",
    "his": 7,
    "manual": 7,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Rameshwar Reddy"
  },
  {
    "id": 91,
    "date": "2026-08-26",
    "ward": "Internal Medicine Ward 5",
    "capacity": 20,
    "occupancy": "80%",
    "his": 16,
    "manual": 16,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Aarav Sharma"
  },
  {
    "id": 92,
    "date": "2026-08-26",
    "ward": "Surgery Ward 1",
    "capacity": 20,
    "occupancy": "85%",
    "his": 17,
    "manual": 16,
    "delta": -1,
    "status": "Audit Req",
    "nurse": "Nurse Geeta Sen"
  },
  {
    "id": 93,
    "date": "2026-08-26",
    "ward": "Surgery Ward 2",
    "capacity": 20,
    "occupancy": "85%",
    "his": 17,
    "manual": 18,
    "delta": 1,
    "status": "Imputed",
    "nurse": "Nurse Pooja Hegde"
  },
  {
    "id": 94,
    "date": "2026-08-26",
    "ward": "Surgery Ward 3",
    "capacity": 20,
    "occupancy": "90%",
    "his": 18,
    "manual": 18,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Rohan Mehra"
  },
  {
    "id": 95,
    "date": "2026-08-26",
    "ward": "Surgery Ward 4",
    "capacity": 15,
    "occupancy": "67%",
    "his": 10,
    "manual": 10,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Isha Mukherjee"
  },
  {
    "id": 96,
    "date": "2026-08-26",
    "ward": "Surgery Ward 5",
    "capacity": 15,
    "occupancy": "73%",
    "his": 11,
    "manual": 11,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Sanjay Gupta"
  },
  {
    "id": 97,
    "date": "2026-08-26",
    "ward": "Pediatrics Ward 1",
    "capacity": 10,
    "occupancy": "70%",
    "his": 7,
    "manual": 7,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Divya Nair"
  },
  {
    "id": 98,
    "date": "2026-08-26",
    "ward": "Pediatrics Ward 2",
    "capacity": 20,
    "occupancy": "80%",
    "his": 16,
    "manual": 17,
    "delta": 1,
    "status": "Imputed",
    "nurse": "Nurse Rajesh Khanna"
  },
  {
    "id": 99,
    "date": "2026-08-26",
    "ward": "Pediatrics Ward 3",
    "capacity": 15,
    "occupancy": "80%",
    "his": 12,
    "manual": 11,
    "delta": -1,
    "status": "Audit Req",
    "nurse": "Nurse Swati Deshmukh"
  },
  {
    "id": 100,
    "date": "2026-08-26",
    "ward": "Pediatrics Ward 4",
    "capacity": 10,
    "occupancy": "80%",
    "his": 8,
    "manual": 8,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Nitin Gadkari"
  },
  {
    "id": 101,
    "date": "2026-08-26",
    "ward": "Pediatrics Ward 5",
    "capacity": 15,
    "occupancy": "87%",
    "his": 13,
    "manual": 13,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Meera Joshi"
  },
  {
    "id": 102,
    "date": "2026-08-26",
    "ward": "Orthopedics Ward 1",
    "capacity": 15,
    "occupancy": "93%",
    "his": 14,
    "manual": 14,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Harish Iyer"
  },
  {
    "id": 103,
    "date": "2026-08-26",
    "ward": "Orthopedics Ward 2",
    "capacity": 15,
    "occupancy": "67%",
    "his": 10,
    "manual": 11,
    "delta": 1,
    "status": "Imputed",
    "nurse": "Nurse Preeti Pillai"
  },
  {
    "id": 104,
    "date": "2026-08-26",
    "ward": "Orthopedics Ward 3",
    "capacity": 20,
    "occupancy": "75%",
    "his": 15,
    "manual": 15,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Karan Singhania"
  },
  {
    "id": 105,
    "date": "2026-08-26",
    "ward": "ICU Ward 1",
    "capacity": 10,
    "occupancy": "70%",
    "his": 7,
    "manual": 7,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Tanya Sen"
  },
  {
    "id": 106,
    "date": "2026-08-26",
    "ward": "ICU Ward 2",
    "capacity": 20,
    "occupancy": "80%",
    "his": 16,
    "manual": 15,
    "delta": -1,
    "status": "Audit Req",
    "nurse": "Nurse Gaurav Kapoor"
  },
  {
    "id": 107,
    "date": "2026-08-26",
    "ward": "ICU Ward 3",
    "capacity": 15,
    "occupancy": "80%",
    "his": 12,
    "manual": 12,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Shreya Ghoshal"
  },
  {
    "id": 108,
    "date": "2026-08-26",
    "ward": "ICU Ward 4",
    "capacity": 20,
    "occupancy": "85%",
    "his": 17,
    "manual": 18,
    "delta": 1,
    "status": "Imputed",
    "nurse": "Nurse Alok Nath"
  },
  {
    "id": 109,
    "date": "2026-08-25",
    "ward": "Emergency Ward 1",
    "capacity": 10,
    "occupancy": "80%",
    "his": 8,
    "manual": 9,
    "delta": 1,
    "status": "Imputed",
    "nurse": "Nurse Arjun Singh"
  },
  {
    "id": 110,
    "date": "2026-08-25",
    "ward": "Emergency Ward 2",
    "capacity": 15,
    "occupancy": "80%",
    "his": 12,
    "manual": 12,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Sunita Patel"
  },
  {
    "id": 111,
    "date": "2026-08-25",
    "ward": "Emergency Ward 3",
    "capacity": 10,
    "occupancy": "80%",
    "his": 8,
    "manual": 7,
    "delta": -1,
    "status": "Audit Req",
    "nurse": "Nurse Vikram Malhotra"
  },
  {
    "id": 112,
    "date": "2026-08-25",
    "ward": "Emergency Ward 4",
    "capacity": 20,
    "occupancy": "90%",
    "his": 18,
    "manual": 18,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Manish Joshi"
  },
  {
    "id": 113,
    "date": "2026-08-25",
    "ward": "Emergency Ward 5",
    "capacity": 20,
    "occupancy": "90%",
    "his": 18,
    "manual": 18,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Kavita Rao"
  },
  {
    "id": 114,
    "date": "2026-08-25",
    "ward": "Internal Medicine Ward 1",
    "capacity": 10,
    "occupancy": "70%",
    "his": 7,
    "manual": 8,
    "delta": 1,
    "status": "Imputed",
    "nurse": "Nurse Deepak Choudhary"
  },
  {
    "id": 115,
    "date": "2026-08-25",
    "ward": "Internal Medicine Ward 2",
    "capacity": 15,
    "occupancy": "73%",
    "his": 11,
    "manual": 11,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Ananya Mishra"
  },
  {
    "id": 116,
    "date": "2026-08-25",
    "ward": "Internal Medicine Ward 3",
    "capacity": 10,
    "occupancy": "70%",
    "his": 7,
    "manual": 7,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Rameshwar Reddy"
  },
  {
    "id": 117,
    "date": "2026-08-25",
    "ward": "Internal Medicine Ward 4",
    "capacity": 10,
    "occupancy": "80%",
    "his": 8,
    "manual": 8,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Aarav Sharma"
  },
  {
    "id": 118,
    "date": "2026-08-25",
    "ward": "Internal Medicine Ward 5",
    "capacity": 20,
    "occupancy": "80%",
    "his": 16,
    "manual": 15,
    "delta": -1,
    "status": "Audit Req",
    "nurse": "Nurse Geeta Sen"
  },
  {
    "id": 119,
    "date": "2026-08-25",
    "ward": "Surgery Ward 1",
    "capacity": 20,
    "occupancy": "85%",
    "his": 17,
    "manual": 18,
    "delta": 1,
    "status": "Imputed",
    "nurse": "Nurse Pooja Hegde"
  },
  {
    "id": 120,
    "date": "2026-08-25",
    "ward": "Surgery Ward 2",
    "capacity": 20,
    "occupancy": "90%",
    "his": 18,
    "manual": 18,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Rohan Mehra"
  },
  {
    "id": 121,
    "date": "2026-08-25",
    "ward": "Surgery Ward 3",
    "capacity": 20,
    "occupancy": "90%",
    "his": 18,
    "manual": 18,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Isha Mukherjee"
  },
  {
    "id": 122,
    "date": "2026-08-25",
    "ward": "Surgery Ward 4",
    "capacity": 15,
    "occupancy": "67%",
    "his": 10,
    "manual": 10,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Sanjay Gupta"
  },
  {
    "id": 123,
    "date": "2026-08-25",
    "ward": "Surgery Ward 5",
    "capacity": 15,
    "occupancy": "73%",
    "his": 11,
    "manual": 11,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Divya Nair"
  },
  {
    "id": 124,
    "date": "2026-08-25",
    "ward": "Pediatrics Ward 1",
    "capacity": 10,
    "occupancy": "70%",
    "his": 7,
    "manual": 8,
    "delta": 1,
    "status": "Imputed",
    "nurse": "Nurse Rajesh Khanna"
  },
  {
    "id": 125,
    "date": "2026-08-25",
    "ward": "Pediatrics Ward 2",
    "capacity": 20,
    "occupancy": "80%",
    "his": 16,
    "manual": 15,
    "delta": -1,
    "status": "Audit Req",
    "nurse": "Nurse Swati Deshmukh"
  },
  {
    "id": 126,
    "date": "2026-08-25",
    "ward": "Pediatrics Ward 3",
    "capacity": 15,
    "occupancy": "80%",
    "his": 12,
    "manual": 12,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Nitin Gadkari"
  },
  {
    "id": 127,
    "date": "2026-08-25",
    "ward": "Pediatrics Ward 4",
    "capacity": 10,
    "occupancy": "80%",
    "his": 8,
    "manual": 8,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Meera Joshi"
  },
  {
    "id": 128,
    "date": "2026-08-25",
    "ward": "Pediatrics Ward 5",
    "capacity": 15,
    "occupancy": "87%",
    "his": 13,
    "manual": 13,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Harish Iyer"
  },
  {
    "id": 129,
    "date": "2026-08-25",
    "ward": "Orthopedics Ward 1",
    "capacity": 15,
    "occupancy": "67%",
    "his": 10,
    "manual": 11,
    "delta": 1,
    "status": "Imputed",
    "nurse": "Nurse Preeti Pillai"
  },
  {
    "id": 130,
    "date": "2026-08-25",
    "ward": "Orthopedics Ward 2",
    "capacity": 15,
    "occupancy": "73%",
    "his": 11,
    "manual": 11,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Karan Singhania"
  },
  {
    "id": 131,
    "date": "2026-08-25",
    "ward": "Orthopedics Ward 3",
    "capacity": 20,
    "occupancy": "75%",
    "his": 15,
    "manual": 15,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Tanya Sen"
  },
  {
    "id": 132,
    "date": "2026-08-25",
    "ward": "ICU Ward 1",
    "capacity": 10,
    "occupancy": "70%",
    "his": 7,
    "manual": 6,
    "delta": -1,
    "status": "Audit Req",
    "nurse": "Nurse Gaurav Kapoor"
  },
  {
    "id": 133,
    "date": "2026-08-25",
    "ward": "ICU Ward 2",
    "capacity": 20,
    "occupancy": "80%",
    "his": 16,
    "manual": 16,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Shreya Ghoshal"
  },
  {
    "id": 134,
    "date": "2026-08-25",
    "ward": "ICU Ward 3",
    "capacity": 15,
    "occupancy": "80%",
    "his": 12,
    "manual": 13,
    "delta": 1,
    "status": "Imputed",
    "nurse": "Nurse Alok Nath"
  },
  {
    "id": 135,
    "date": "2026-08-25",
    "ward": "ICU Ward 4",
    "capacity": 20,
    "occupancy": "85%",
    "his": 17,
    "manual": 17,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Kalyani Roy"
  },
  {
    "id": 136,
    "date": "2026-08-24",
    "ward": "Emergency Ward 1",
    "capacity": 10,
    "occupancy": "80%",
    "his": 8,
    "manual": 8,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Sunita Patel"
  },
  {
    "id": 137,
    "date": "2026-08-24",
    "ward": "Emergency Ward 2",
    "capacity": 15,
    "occupancy": "80%",
    "his": 12,
    "manual": 11,
    "delta": -1,
    "status": "Audit Req",
    "nurse": "Nurse Vikram Malhotra"
  },
  {
    "id": 138,
    "date": "2026-08-24",
    "ward": "Emergency Ward 3",
    "capacity": 10,
    "occupancy": "80%",
    "his": 8,
    "manual": 8,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Manish Joshi"
  },
  {
    "id": 139,
    "date": "2026-08-24",
    "ward": "Emergency Ward 4",
    "capacity": 20,
    "occupancy": "90%",
    "his": 18,
    "manual": 18,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Kavita Rao"
  },
  {
    "id": 140,
    "date": "2026-08-24",
    "ward": "Emergency Ward 5",
    "capacity": 20,
    "occupancy": "70%",
    "his": 14,
    "manual": 15,
    "delta": 1,
    "status": "Imputed",
    "nurse": "Nurse Deepak Choudhary"
  },
  {
    "id": 141,
    "date": "2026-08-24",
    "ward": "Internal Medicine Ward 1",
    "capacity": 10,
    "occupancy": "70%",
    "his": 7,
    "manual": 7,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Ananya Mishra"
  },
  {
    "id": 142,
    "date": "2026-08-24",
    "ward": "Internal Medicine Ward 2",
    "capacity": 15,
    "occupancy": "73%",
    "his": 11,
    "manual": 11,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Rameshwar Reddy"
  },
  {
    "id": 143,
    "date": "2026-08-24",
    "ward": "Internal Medicine Ward 3",
    "capacity": 10,
    "occupancy": "70%",
    "his": 7,
    "manual": 7,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Aarav Sharma"
  },
  {
    "id": 144,
    "date": "2026-08-24",
    "ward": "Internal Medicine Ward 4",
    "capacity": 10,
    "occupancy": "80%",
    "his": 8,
    "manual": 7,
    "delta": -1,
    "status": "Audit Req",
    "nurse": "Nurse Geeta Sen"
  },
  {
    "id": 145,
    "date": "2026-08-24",
    "ward": "Internal Medicine Ward 5",
    "capacity": 20,
    "occupancy": "85%",
    "his": 17,
    "manual": 18,
    "delta": 1,
    "status": "Imputed",
    "nurse": "Nurse Pooja Hegde"
  },
  {
    "id": 146,
    "date": "2026-08-24",
    "ward": "Surgery Ward 1",
    "capacity": 20,
    "occupancy": "85%",
    "his": 17,
    "manual": 17,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Rohan Mehra"
  },
  {
    "id": 147,
    "date": "2026-08-24",
    "ward": "Surgery Ward 2",
    "capacity": 20,
    "occupancy": "90%",
    "his": 18,
    "manual": 18,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Isha Mukherjee"
  },
  {
    "id": 148,
    "date": "2026-08-24",
    "ward": "Surgery Ward 3",
    "capacity": 20,
    "occupancy": "70%",
    "his": 14,
    "manual": 14,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Sanjay Gupta"
  },
  {
    "id": 149,
    "date": "2026-08-24",
    "ward": "Surgery Ward 4",
    "capacity": 15,
    "occupancy": "73%",
    "his": 11,
    "manual": 11,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Divya Nair"
  },
  {
    "id": 150,
    "date": "2026-08-24",
    "ward": "Surgery Ward 5",
    "capacity": 15,
    "occupancy": "73%",
    "his": 11,
    "manual": 12,
    "delta": 1,
    "status": "Imputed",
    "nurse": "Nurse Rajesh Khanna"
  },
  {
    "id": 151,
    "date": "2026-08-24",
    "ward": "Pediatrics Ward 1",
    "capacity": 10,
    "occupancy": "80%",
    "his": 8,
    "manual": 7,
    "delta": -1,
    "status": "Audit Req",
    "nurse": "Nurse Swati Deshmukh"
  },
  {
    "id": 152,
    "date": "2026-08-24",
    "ward": "Pediatrics Ward 2",
    "capacity": 20,
    "occupancy": "80%",
    "his": 16,
    "manual": 16,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Nitin Gadkari"
  },
  {
    "id": 153,
    "date": "2026-08-24",
    "ward": "Pediatrics Ward 3",
    "capacity": 15,
    "occupancy": "87%",
    "his": 13,
    "manual": 13,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Meera Joshi"
  },
  {
    "id": 154,
    "date": "2026-08-24",
    "ward": "Pediatrics Ward 4",
    "capacity": 10,
    "occupancy": "90%",
    "his": 9,
    "manual": 9,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Harish Iyer"
  },
  {
    "id": 155,
    "date": "2026-08-24",
    "ward": "Pediatrics Ward 5",
    "capacity": 15,
    "occupancy": "93%",
    "his": 14,
    "manual": 15,
    "delta": 1,
    "status": "Imputed",
    "nurse": "Nurse Preeti Pillai"
  },
  {
    "id": 156,
    "date": "2026-08-24",
    "ward": "Orthopedics Ward 1",
    "capacity": 15,
    "occupancy": "67%",
    "his": 10,
    "manual": 10,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Karan Singhania"
  },
  {
    "id": 157,
    "date": "2026-08-24",
    "ward": "Orthopedics Ward 2",
    "capacity": 15,
    "occupancy": "73%",
    "his": 11,
    "manual": 11,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Tanya Sen"
  },
  {
    "id": 158,
    "date": "2026-08-24",
    "ward": "Orthopedics Ward 3",
    "capacity": 20,
    "occupancy": "75%",
    "his": 15,
    "manual": 14,
    "delta": -1,
    "status": "Audit Req",
    "nurse": "Nurse Gaurav Kapoor"
  },
  {
    "id": 159,
    "date": "2026-08-24",
    "ward": "ICU Ward 1",
    "capacity": 10,
    "occupancy": "80%",
    "his": 8,
    "manual": 8,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Shreya Ghoshal"
  },
  {
    "id": 160,
    "date": "2026-08-24",
    "ward": "ICU Ward 2",
    "capacity": 20,
    "occupancy": "85%",
    "his": 17,
    "manual": 18,
    "delta": 1,
    "status": "Imputed",
    "nurse": "Nurse Alok Nath"
  },
  {
    "id": 161,
    "date": "2026-08-24",
    "ward": "ICU Ward 3",
    "capacity": 15,
    "occupancy": "87%",
    "his": 13,
    "manual": 13,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Kalyani Roy"
  },
  {
    "id": 162,
    "date": "2026-08-24",
    "ward": "ICU Ward 4",
    "capacity": 20,
    "occupancy": "90%",
    "his": 18,
    "manual": 18,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Vikas Dubey"
  },
  {
    "id": 163,
    "date": "2026-08-23",
    "ward": "Emergency Ward 1",
    "capacity": 10,
    "occupancy": "80%",
    "his": 8,
    "manual": 7,
    "delta": -1,
    "status": "Audit Req",
    "nurse": "Nurse Vikram Malhotra"
  },
  {
    "id": 164,
    "date": "2026-08-23",
    "ward": "Emergency Ward 2",
    "capacity": 15,
    "occupancy": "87%",
    "his": 13,
    "manual": 13,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Manish Joshi"
  },
  {
    "id": 165,
    "date": "2026-08-23",
    "ward": "Emergency Ward 3",
    "capacity": 10,
    "occupancy": "90%",
    "his": 9,
    "manual": 9,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Kavita Rao"
  },
  {
    "id": 166,
    "date": "2026-08-23",
    "ward": "Emergency Ward 4",
    "capacity": 20,
    "occupancy": "90%",
    "his": 18,
    "manual": 19,
    "delta": 1,
    "status": "Imputed",
    "nurse": "Nurse Deepak Choudhary"
  },
  {
    "id": 167,
    "date": "2026-08-23",
    "ward": "Emergency Ward 5",
    "capacity": 20,
    "occupancy": "70%",
    "his": 14,
    "manual": 14,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Ananya Mishra"
  },
  {
    "id": 168,
    "date": "2026-08-23",
    "ward": "Internal Medicine Ward 1",
    "capacity": 10,
    "occupancy": "70%",
    "his": 7,
    "manual": 7,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Rameshwar Reddy"
  },
  {
    "id": 169,
    "date": "2026-08-23",
    "ward": "Internal Medicine Ward 2",
    "capacity": 15,
    "occupancy": "73%",
    "his": 11,
    "manual": 11,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Aarav Sharma"
  },
  {
    "id": 170,
    "date": "2026-08-23",
    "ward": "Internal Medicine Ward 3",
    "capacity": 10,
    "occupancy": "80%",
    "his": 8,
    "manual": 7,
    "delta": -1,
    "status": "Audit Req",
    "nurse": "Nurse Geeta Sen"
  },
  {
    "id": 171,
    "date": "2026-08-23",
    "ward": "Internal Medicine Ward 4",
    "capacity": 10,
    "occupancy": "80%",
    "his": 8,
    "manual": 9,
    "delta": 1,
    "status": "Imputed",
    "nurse": "Nurse Pooja Hegde"
  },
  {
    "id": 172,
    "date": "2026-08-23",
    "ward": "Internal Medicine Ward 5",
    "capacity": 20,
    "occupancy": "85%",
    "his": 17,
    "manual": 17,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Rohan Mehra"
  },
  {
    "id": 173,
    "date": "2026-08-23",
    "ward": "Surgery Ward 1",
    "capacity": 20,
    "occupancy": "90%",
    "his": 18,
    "manual": 18,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Isha Mukherjee"
  },
  {
    "id": 174,
    "date": "2026-08-23",
    "ward": "Surgery Ward 2",
    "capacity": 20,
    "occupancy": "90%",
    "his": 18,
    "manual": 18,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Sanjay Gupta"
  },
  {
    "id": 175,
    "date": "2026-08-23",
    "ward": "Surgery Ward 3",
    "capacity": 20,
    "occupancy": "70%",
    "his": 14,
    "manual": 14,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Divya Nair"
  },
  {
    "id": 176,
    "date": "2026-08-23",
    "ward": "Surgery Ward 4",
    "capacity": 15,
    "occupancy": "73%",
    "his": 11,
    "manual": 12,
    "delta": 1,
    "status": "Imputed",
    "nurse": "Nurse Rajesh Khanna"
  },
  {
    "id": 177,
    "date": "2026-08-23",
    "ward": "Surgery Ward 5",
    "capacity": 15,
    "occupancy": "73%",
    "his": 11,
    "manual": 10,
    "delta": -1,
    "status": "Audit Req",
    "nurse": "Nurse Swati Deshmukh"
  },
  {
    "id": 178,
    "date": "2026-08-23",
    "ward": "Pediatrics Ward 1",
    "capacity": 10,
    "occupancy": "80%",
    "his": 8,
    "manual": 8,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Nitin Gadkari"
  },
  {
    "id": 179,
    "date": "2026-08-23",
    "ward": "Pediatrics Ward 2",
    "capacity": 20,
    "occupancy": "85%",
    "his": 17,
    "manual": 17,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Meera Joshi"
  },
  {
    "id": 180,
    "date": "2026-08-23",
    "ward": "Pediatrics Ward 3",
    "capacity": 15,
    "occupancy": "87%",
    "his": 13,
    "manual": 13,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Harish Iyer"
  },
  {
    "id": 181,
    "date": "2026-08-23",
    "ward": "Pediatrics Ward 4",
    "capacity": 10,
    "occupancy": "90%",
    "his": 9,
    "manual": 10,
    "delta": 1,
    "status": "Imputed",
    "nurse": "Nurse Preeti Pillai"
  },
  {
    "id": 182,
    "date": "2026-08-23",
    "ward": "Pediatrics Ward 5",
    "capacity": 15,
    "occupancy": "67%",
    "his": 10,
    "manual": 10,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Karan Singhania"
  },
  {
    "id": 183,
    "date": "2026-08-23",
    "ward": "Orthopedics Ward 1",
    "capacity": 15,
    "occupancy": "73%",
    "his": 11,
    "manual": 11,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Tanya Sen"
  },
  {
    "id": 184,
    "date": "2026-08-23",
    "ward": "Orthopedics Ward 2",
    "capacity": 15,
    "occupancy": "73%",
    "his": 11,
    "manual": 10,
    "delta": -1,
    "status": "Audit Req",
    "nurse": "Nurse Gaurav Kapoor"
  },
  {
    "id": 185,
    "date": "2026-08-23",
    "ward": "Orthopedics Ward 3",
    "capacity": 20,
    "occupancy": "80%",
    "his": 16,
    "manual": 16,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Shreya Ghoshal"
  },
  {
    "id": 186,
    "date": "2026-08-23",
    "ward": "ICU Ward 1",
    "capacity": 10,
    "occupancy": "80%",
    "his": 8,
    "manual": 9,
    "delta": 1,
    "status": "Imputed",
    "nurse": "Nurse Alok Nath"
  },
  {
    "id": 187,
    "date": "2026-08-23",
    "ward": "ICU Ward 2",
    "capacity": 20,
    "occupancy": "85%",
    "his": 17,
    "manual": 17,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Kalyani Roy"
  },
  {
    "id": 188,
    "date": "2026-08-23",
    "ward": "ICU Ward 3",
    "capacity": 15,
    "occupancy": "87%",
    "his": 13,
    "manual": 13,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Vikas Dubey"
  },
  {
    "id": 189,
    "date": "2026-08-23",
    "ward": "ICU Ward 4",
    "capacity": 20,
    "occupancy": "90%",
    "his": 18,
    "manual": 18,
    "delta": 0,
    "status": "Reconciled",
    "nurse": "Nurse Smriti Irani"
  }
];
